name: flutter_admin_scaffold
description: A scaffold class with a sideBar that works with a appBar.
version: 1.4.1
homepage: https://github.com/keyber-inc/flutter_admin_scaffold

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

