name: flutter_admin_scaffold
description: A scaffold class with a sideBar that works with a appBar.
version: 1.4.1
homepage: https://github.com/keyber-inc/flutter_admin_scaffold

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  persistent_bottom_nav_bar_v2: ^6.0.1
  go_router: ^16.0.0
  badges: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
